services:
  mysql_8:
    container_name: hrm_mysql_8
    image: mysql:8.4
    env_file:
      - .env
    environment:
      TZ: 'Asia/Taipei'
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - './data/mysql-data:/opt/mysql-data'
      - './config/my.cnf:/etc/mysql/my.cnf'
      - './data/mysql-logs:/opt/logs'
  redis_7:
    container_name: hrm_redis_7
    image: 'redis:7.2'
    ports:
      - '6379:6379'