package com.hrms.enums;

import lombok.Getter;

@Getter
public enum ErrorCode {
    // 通用錯誤碼
    FAILURE(1, "fail"),
    INVALID_REQUEST(1001, "Invalid Request"),
    NOT_FOUND(1002, "Resource Not Found"),
    INTERNAL_SERVER_ERROR(1003, "Internal Server Error"),
    UNAUTHORIZED(1004, "Unauthorized Access"),
    FORBIDDEN(1005, "Forbidden Access"),
    INVALID_PARAMETER(1006, "Invalid parameter"),
    GENERAL_ERROR(1007, "系統忙碌中，請稍後再試"),
    PARAMETER_TYPE_ERROE(1008, "參數類型錯誤"),
    INVALID_INPUT(1009, "無效的輸入"),
    DATABASE_ERROR(1010, "資料庫錯誤"),
    EMPLOYEE_ERROR(1011, "發生錯誤，該員工不存在"),
    PASSWORD_ERROR(1012, "密碼錯誤"),
    NOT_CURRENT_EMPLOYEE_ERROR(1013, "此帳號為非在職員工!"),
    OLD_PASSWORD_ERROR(1014, "舊密碼錯誤"),
    PASSWORD_CONFIRMATION_MISMATCH(1015, "新密碼和二次確認密碼不相符"),
    ID_AUTO_INCREMENT(1016, "ID為自動遞增"),
    SUPERVISOR_ID_NOT_FOUND(1017, "主管ID不存在"),
    PARENT_DEPARTMENT_NOT_FOUND(1018, "母部門不存在"),
    DEPARTMENT_HAS_EMPLOYEES(1019, "部門存在員工，無法刪除"),
    DEPARTMENT_CREATION_FAILED(1020, "新增部門失敗"),
    DEPARTMENT_ID_NOT_FOUND(1021, "該部門ID不存在"),
    NOTICE_END_TIME_EARLIER_THAN_START(1022, "公告結束時間不能早於發佈時間"),
    NOTICE_ID_NOT_FOUND(1023, "該公告ID不存在"),
    EMAIL_SENDING_ERROR(1024, "寄送email失敗"),
    NO_PERMISSION(1025, "無權限操作"),
    WRONG_PASSWORD(1026, "新密碼不能跟舊密碼一樣"),
    ROLE_ERROR(1027, "發生錯誤，該角色不存在"),
    SUBMIT_NOTIFICATION_ID_NOT_FOUND(1028, "該通知ID不存在"),
    ROLE_IS_NOT_NULL(1029, "角色id不存在"),
    EMPLOYEE_ROLE_IS_NOT_NULL(1030, "員工角色不存在"),
    FILE_UPLOAD_ERROR(1031, "檔案上傳失敗"),
    INVALID_FILE_TYPE_OR_SIZE(1032, "檔案類型不正確或檔案大小超過限制"),
    INVALID_FILE_NAME(1033, "檔名不要有中文"),
    LEAVE_RECORD_END_TIME_EARLIER_THAN_START(1034, "請假結束時間不能早於開始時間"),
    LEAVE_RECORD_ID_NOT_FOUND(1035, "該請假紀錄ID不存在"),
    HISTORY_REVIEW_UPDATE_FAIL(1036, "更新歷史紀錄失敗"),
    NO_APPROVAL_PERMISSION(1037, "無權限審核這筆紀錄"),
    LEAVE_RECORD_COUNT_FAIL(1038, "請假天數出現錯誤"),
    COMMENT_UPDATE_FAIL(1039, "更新審核意見失敗"),
    LEAVE_SPECIAL_RECORD_END_TIME_EARLIER_THAN_START(1040, "假別失效時間不能早於生效時間"),
    LEAVE_SPECIAL_RECORD_ID_NOT_FOUND(1041, "該假別ID不存在"),
    LEAVE_RECORD_REJECT_FAIL(1042, "該紀錄不能駁回"),
    LEAVE_RECORD_TYPE_NOT_IN_RECORD_SETTINGS(1043, "申請的請假類型不在該員工的假別設定中"),
    LEAVE_RECORD_TYPE_EXPIRED_OR_NOT_EFFECTIVE(1044, "該假別設定已過期或尚未生效"),
    LEAVE_RECORD_DURATION_BELOW_MIN_UNIT(1045, "請假時長不符合最小單位限制"),
    LEAVE_RECORD_EXCEEDS_MAX_DAYS(1046, "已超過該假別的最大可請假天數"),
    LEAVE_RECORD_MUST_BE_CONTINUOUS(1047, "必須一次性請完所有天數"),
    LEAVE_RECORD_ADVANCE_APPLICATION_REQUIRED(1048, "請假申請必須提前提交"),
    INVALID_SHIFT_TIME(1049, "不符合班別的時間段"),
    INVALID_SHIFT_TYPE(1050, "無效的班別"),
    LEAVE_RECORD_DURATION_EXCEEDS_MAX_LIMIT(1051, "超過單日請假最大時長"),
    LEAVE_RECORD_TIME_OVERLAPS(1052, "不可出現重複的請假時段"),
    UPDATE_LEAVE_RECORD_RECORDS_FAIL(1053, "更新請假假別失敗，更新筆數大於1"),
    LEAVE_RECORD_MULTIPLE_SHIFT_ON_SAME_DAY(1054, "同一天不能請多個班次的假"),
    ANNUAL_LEAVE_NOT_FOUND(1055, "找不到該員工的特休假別"),
    ANNUAL_LEAVE_MUST_BE_EXHAUSTED_BEFORE_OPTIONAL_LEAVE(1056, "選休假必須要等特休請完才能申請"),
    LEAVE_DATES_CANNOT_BE_EMPTY(1057, "請假時間不可為空"),
    INVALID_LEAVE_RECORD_APPROVAL_STAGE(1058, "無效的請假流程狀態"),
    LEAVE_RECORD_CANCEL_FAIL(1059, "這筆請假紀錄無法銷假"),
    NO_CANCEL_PERMISSION(1060, "無銷假權限"),
    ACCOUNT_ERROR(1061, "帳號已存在"),
    INCLUDE_BREAK_ERROR(1062, "是否包含午休時間為必填"),
    CONFIG_KEY_ALREADY_EXISTS(1063, "已有相同的key存在"),
    CONFIG_ID_NOT_FOUND(1064, "該配置ID不存在"),
    INVALID_CONFIG_KEY(1065, "不符合配置key命名規則"),
    INVALID_CSV_HEADER(1066, "CSV檔案的標頭不符合要求"),
    DUPLICATE_SHIFT_SCHEDULE(1067, "該日期已存在班表"),
    INVALID_CSV_FORMAT(1068, "CSV 格式錯誤"),
    INVALID_DATE_FORMAT(1069, "日期格式錯誤"),
    INVALID_EMPLOYEE_ENTRY_DATE(1070, "無效的員工入職日"),
    ADMIN_SHIFT_SCHEDULE_NOT_FOUND(1071, "預設班表不存在"),
    INVALID_SHIFT_SCHEDULE_STATUS(1072, "排班狀態不存在"),
    INVALID_SHIFT_SCHEDULE_CSV_YEAR(1073, "排班CSV年度錯誤"),
    EMPTY_CSV_DATA(1074, "CSV檔案內容為空"),
    END_TIME_EARLIER_THAN_START(1075, "結束時間不能早於開始時間"),
    INVALID_FILE_CONTENT(1076, "檔案內容錯誤"),
    EMPTY_SHIFT_SCHEDULES(1077, "排班班表不存在"),
    INVALID_SHIFT_DATE_RANGE(1078, "不在同一個雙週週期內"),
    EXCEEDS_SIX_DAY_WORK_RULE(1079, "連續工作超過六天"),
    ATTENDANCE_RECORDS_CLOCK_IN_TIME_AFTER_CLOCK_OUT_TIME(1080, "上班時間不能晚於下班時間"),
    ATTENDANCE_RECORDS_ID_NOT_FOUND(1081, "出勤紀錄ID不存在"),
    EXPORT_FORMAT(1802, "無效的格式"),
    ACTION_TYPE_NOT_ALLOWED(1083, "不可排已鎖定的班表"),
    INVALID_PERIOD_START_DATE(1084, "區間開始日期需在2023-12-31之後"),
    DEPARTMENT_ACCESS_DENIED(1085, "無權限編輯其他部門的排班"),
    SHIFT_DATE_NOT_CONTINUOUS(1086, "排班日期不連續"),
    SHIFT_SCHEDULES_WRONG_SIZE(1087, "排班需一次修改兩週資料"),
    SHIFT_SCHEDULES_NOT_EXISTS(1088, "排班資料不存在"),
    SHIFT_SCHEDULES_WRONG_DATE(1089, "排班日期與資料庫不一致"),
    SHIFT_SCHEDULES_WRONG_RANGE(1090, "排班資料不符合區間"),
    SHIFT_TYPE_NOT_SCHEDULED(1091, "該班別非排班制的班別"),
    INSUFFICIENT_SHIFT_COUNTS(1092, "未符合排班最小人數要求"),
    NATIONAL_HOLIDAY_SCHEDULE_MISSING(1093, "員工未依規定放國定假日"),
    INVALID_SHIFT_CATEGORY(1094, "排班的班別時段未設置"),
    ATTENDANCE_SUMMARY_REPORT_WRONG_DATE(1095, "考勤月報表日期格式錯誤"),
    ATTENDANCE_SUMMARY_REPORT_EXISTS(1096, "該月份考勤月報表已存在"),
    EXPORT_FAIL(1097, "導出異常，請聯繫系統工程師"),
    NOT_ENOUGH_REST_HOURS(1098, "休息時間未超過11小時"),
    REST_DAY_RULE_VIOLATION(1099, "未符合一例一休規則"),
    OVERTIME_DURATION_BELOW_MIN_LIMIT(1100, "加班時數少於最小限制（1小時）"),
    OVERTIME_DURATION_EXCEEDS_MAX_LIMIT(1101, "加班時數超過最大限制（4小時）"),
    OVERTIME_RECORD_TIME_OVERLAPS(1102, "不可出現重複的加班時段"),
    INVALID_OVERTIME_RECORD_APPROVAL_STAGE(1103, "無效的加班流程狀態"),
    OVERTIME_CONVERSION_NOT_ALLOWED(1104, "該員工加班不允許換錢"),
    OVERTIME_RECORD_CANCEL_FAIL(1105, "此筆加班紀錄無法取消"),
    NOTIFICATION_DELETE_UNAUTHORIZED(1106, "只能刪除自己的通知"),
    INVALID_SHIFT_TYPE_CONFIG_KEY(1107, "班別配置無效，必須以 'SHIFT_TYPE_'作為前綴或'HOLIDAY'作為後綴"),
    INVALID_SHIFT_COLOR_CODE(1108, "不符合班別色碼格式"),
    NO_GROUP_LEADER_OR_EMAIL_NOT_SET(1109, "該部門無組長或組長無設定信箱")
    ;
    private final int code;
    private final String message;

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

}
