INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (1, '0001', '考察管理', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (2, '000101', '工作排班', '0001', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (3, '000102', '迟到早退监控', '0001', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (4, '000103', '请假加班', '0001', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (5, '000104', '请假加班', '0001', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (6, '000105', '考勤报表', '0001', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (7, '0001031', '可修假日期', '000103', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (8, '0001032', '特修递延计算', '000103', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (9, '0001051', '工时统计', '000105', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (10, '0002', '薪酬管理', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (11, '000201', '薪资计算', '0002', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (12, '000202', '薪资报表', '0002', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (13, '000203', '电子签核', '0002', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (14, '0002011', '应领', '000201', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (15, '0002012', '应扣', '000201', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (16, '0002013', '奖金', '000201', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (17, '0002031', '线上课程费用', '000203', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (18, '0002032', '团建费用', '0002032', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (19, '0003', '人事资料管理', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (20, '000301', '部门资料', '0003', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (21, '000302', '员工资料', '0003', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (22, '0003011', '部门名称', '000301', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (23, '0003012', '职称', '000301', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (24, '0004', '绩效评估', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (25, '000401', '线上KPI', '0004', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (26, '000402', '主管考核', '0004', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (27, '000403', '考核报表', '0004', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (28, '0005', '资讯中心', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (29, '000501', '组织图', '0005', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (30, '000502', '座位图', '0005', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (31, '000503', '通讯录', '0005', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (32, '000504', '通知与公告', '0005', 1, 1, 1, '', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`menu` (`id`, `code`, `text`, `super_code`, `cate`, `showed`, `sort`, `remark`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (33, '0006', '权限管理', '', 1, 1, 1, '', NULL, NULL, NULL, NULL);


INSERT INTO `hrm`.`role` (`id`, `role_name`, `menu_permission`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (1, 'ADMIN', '0001,000101,000102,000103,000104,000105,0001031,0001032,0001051,0002,000201,000202,000203,0002011,0002012,0002013,0002031,0002032,0003,000301,000302,0003011,0003012,0004,000401,000402,000403,0005,000501,000502,000503,000504,0006', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`role` (`id`, `role_name`, `menu_permission`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (2, 'LEADER', '000101,000102,000103,000104', NULL, NULL, NULL, NULL);
INSERT INTO `hrm`.`role` (`id`, `role_name`, `menu_permission`, `created_date`, `updated_date`, `created_id`, `updated_id`) VALUES (3, 'EMPlOYEE', '000101,000102,000103,000104', NULL, NULL, NULL, NULL);

INSERT INTO `hrm`.`employee_roles` (`employee_id`, `role_id`) VALUES (1, 1);

